# BEGIN HOFFMAN SFTP
Match User hoffman_files
    ChrootDirectory /srv/hoffman-sftp
    ForceCommand internal-sftp -d /assets -u 0002 -P symlink,hardlink
    AuthorizedKeysFile /etc/ssh/authorized_keys/hoffman_files
    AuthenticationMethods publickey
    PubkeyAuthentication yes
    PasswordAuthentication no
    AllowAgentForwarding no
    AllowTcpForwarding no
    AllowStreamLocalForwarding no
    X11Forwarding no
    PermitTTY no
    PermitTunnel no
    PermitUserRC no
Match all
# END HOFFMAN SFTP
